@startuml
skinparam shadowing false
skinparam monochrome false
skinparam ArrowColor #333333
skinparam BackgroundColor #F9F9F9
skinparam FontName Arial
skinparam FontSize 12

skinparam rectangle {
  BackgroundColor #F7F7F7
  BorderColor #CCCCCC
}
skinparam package {
  BackgroundColor #EFEFEF
  BorderColor #BBBBBB
}

actor Clientele as clientele
actor Conseil as conseil

package "Poste banque (local)" {
  rectangle "Microsoft Dynamics 365 Customer Service Workspace" as agent_workspace #FFE5CC
  component "Ether" as ether #E0F7FF
  component "Microsoft Dynamics CRM" as dynamics_crm #CCCCFF
  file "Scripts" as scripts #E0F7FF
}

component "Chatbot" as chatbot #FFEEEE
component "YX7 - Prise de rendez-vous" as rendezvous #FFEEEE
cloud "Dynamics 365 Customer Service" as dynamics_call_center #FFCCCC
component "Voicebot" as spitch #FFDADA
component "YB1 - Recherche Tiers" as recherche_tiers #FFDADA
component "BBO - Backend conversation" as backend_conversation #FFE5CC
component "BVD - Vision Client 360" as vision_client #CCE5FF

'---- Interactions principales ----
conseil --> agent_workspace :  Réception d’un appel
clientele --> dynamics_call_center : Appel entrant
conseil --> dynamics_call_center : Appel sortant
clientele --> chatbot : Interaction via chat

'---- Gestion des rendez-vous ----
chatbot --> rendezvous : Demande de callback
rendezvous --> dynamics_call_center : Réservation de callback

'---- Recherche et identification ----
dynamics_call_center --> recherche_tiers : Recherche de tiers
dynamics_call_center -- spitch : Débranchement VoiceBot
dynamics_call_center ... agent_workspace

'---- Communication via WebSocket ----
agent_workspace --> scripts : Déclenchement script
scripts --> ether : Envoi d'informations via WebSocket
scripts --> dynamics_crm : Ouverture MS-Dynamics On-Premise
ether --> vision_client : Accès Vision Client 360

'---- Gestion backend ----
spitch --> backend_conversation : Identification de l'appelant
vision_client --> backend_conversation : Compte rendu client

@enduml
